### ISSUE TITLE
Status icons showing only in project root folder

### ISSUE THREAD

**Issue by ghost** [chrisjbillington/git_nautilus_icons#17]
I finally got this extensions as such working (see #16).

However, I only get git status icons on files and folders in the project root; viewing files and folders in sub-folders I don't see any icons at all. No error-messages in console.

Also, `git-nautilus-icons` shows up in Nemo's list of extensions as **`InfoProvider+NemoPython`**` no information available`. Might this mean it's not properly installed, or is it a bug in the extensions?

![Plugins](https://user-images.githubusercontent.com/6561048/110827097-06757b80-8296-11eb-963c-f71bff4d0343.png)

Enclosing screenshot of a git folder.

![Nemo](https://user-images.githubusercontent.com/6561048/110826718-a41c7b00-8295-11eb-8818-1c9ea6cc491c.png)

**Comment by chrisjbillington** [comment]
It showing up as `InfoProvider+NemoPython no information available` must just be because I haven't set some attributes that would set the name. I didn't realise there was anywhere that nemo would list extensions! ([nautilus certainly doesn't show you any such list or allow disabling them](https://gitlab.gnome.org/GNOME/nautilus/-/issues/461)).

I could find out where one sets the name of the extension, but I don't think this indicates anything wrong with the extension - shouldn't affect functionality.

It works for me here on Arch Linux and Nemo 4.8.5 - what version of Nemo are you using?

![image](https://user-images.githubusercontent.com/1044087/110861757-96aec300-828c-11eb-8b7c-56f7429f5d15.png)

**Comment by ghost** [comment]
I'm using Nemo version 4.8.3 on FreeBSD 13 BETA 3. Installed `git-nautilus-icons` version 2.0.0 through `pip`. I can assist you with running test builds of your plugin if you need me to.

**Comment by burny2** [comment]
I had the same problem with Nemo 3.8.5 on Debian 10. I figured out, that symlinks within the path to the project root will prevent icons to show up in the sub-folders, because `get_repo_root()` returns the absolute root path in canonical form, which causes `get_statuses_by_dir()` to fail. Returning a root path based on the given path instead, fixed the problem for me:
```python
def get_repo_root(path):
    """Returns the root directory of a repo, given a directory within it,
    or raises NotARepo if the directory is not in a git repo"""
    if blacklisted(path):
        raise NotARepo
    cmd = ['git', 'rev-parse', '--show-cdup']
    output = git_call(cmd, path).strip()
    return os.path.normpath(os.path.join(path, output))
```

**Comment by chrisjbillington** [comment]
Ah the glory of open source. I would have had no idea how to reproduce this bug, but a stranger comes out of the ether with a fix and we all benefit. After being told that symlinks were the issue I tested and could reproduce the issue, and @burny2's changes resolved the problem.

Thanks @burny2 

Fix released as v2.0.1

**Comment by ghost** [comment]
A huge thanks to the both of you! The reason why this error was apparent in FreeBSD, is that the `/home` folder actually lives in `/usr/home`, and `/home` is just a symblink there. When viewing the "same folder" directly as `/usr/home/niklas/..`, version 2.0.0 displayed the icons correctly. In version 2.0.1 it works no matter where I view it.

I might add, that the plugin still shows up as `InfoProvider+NemoPython no information available` ;)

**Comment by chrisjbillington** [comment]
You're welcome!

> I might add, that the plugin still shows up as InfoProvider+NemoPython no information available ;)

I've had a look through some other extensions' code and the documentation, and can't figure out how to set the name of the extension in a way that will show up there. If anyone else can figure it out, I will be happy to include the changes! If you have any other extensions that do set the name, let me know and we can take a look at their source to see how they do it.

Filed as #18
